<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Title>Console-Grid-Components</Title>
    <Authors>$(Deluge11)</Authors>
    <PackageReadmeFile>readme.md</PackageReadmeFile>
    <PackageLicenseFile>License.txt</PackageLicenseFile>
  </PropertyGroup>

</Project>
